name: deploy

on:
  push:
    branches: [ master ]
    tags: [ v* ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set environment variables from project settings
        run: |
          exec .github/scripts/set-env-from-xcodeproj.sh
      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh
      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh
      - name: Build app
        run: |
          fastlane run build_app
      - name: "Upload artifact (log)"
        uses: actions/upload-artifact@v2
        with:
          name: "build.log"
          path: "~/Library/Logs/gym/*.log"

      - name: "Upload artifact (app)"
        if: success() && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.PRODUCT_NAME }}.ipa"
          path: "${{ env.PRODUCT_NAME }}.ipa"

      - name: "Upload artifact (debugging symbols)"
        if: success() && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.PRODUCT_NAME }}.app.dSYM.zip"
          path: "${{ env.PRODUCT_NAME }}.app.dSYM.zip"

      - name: Upload app to App Store Connect
        if: success() && startsWith(github.ref, 'refs/tags/v')
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f "$PRODUCT_NAME.ipa" -u "$APP_STORE_CONNECT_USERNAME" -p "$APP_STORE_CONNECT_PASSWORD"
